-- Initial schema for tex.center.
--
-- Generated by hand to match packages/db/src/schema.ts. The
-- schema test asserts every table/column declared there appears
-- here. Future migrations append new files; this one is never
-- edited once it has shipped to a real database.

CREATE TABLE users (
    id            uuid        PRIMARY KEY,
    email         text        NOT NULL UNIQUE,
    google_sub    text        NOT NULL UNIQUE,
    display_name  text        NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_id_idx ON sessions(user_id);

CREATE TABLE projects (
    id          uuid        PRIMARY KEY,
    owner_id    uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX projects_owner_id_idx ON projects(owner_id);

CREATE TABLE project_files (
    id            uuid        PRIMARY KEY,
    project_id    uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    path          text        NOT NULL,
    size          bigint      NOT NULL,
    blob_key      text        NOT NULL,
    content_hash  text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, path)
);

CREATE TABLE machine_assignments (
    project_id    uuid        PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    machine_id    text        NOT NULL,
    region        text        NOT NULL,
    state         text        NOT NULL,
    last_seen_at  timestamptz NOT NULL DEFAULT now(),
    created_at    timestamptz NOT NULL DEFAULT now()
);
